pub const HEADING_WHITELIST: [&str; 33] = [
    "Adjective",
    "Adverb",
    "Article",
    "Alternative forms",
    "Conjunction",
    "Etymology",
    "Etymology 1",
    "Etymology 2",
    "Etymology 3",
    "Etymology 4",
    "Etymology 5",
    "Etymology 6",
    "Etymology 7",
    "Etymology 8",
    "Etymology 9",
    "Etymology 10",
    "Etymology 11",
    "Etymology 12",
    "Etymology 13",
    "Etymology 14",
    "Etymology 15",
    "Etymology 16",
    "Etymology 17",
    "Etymology 18",
    "Etymology 19",
    "Etymology 20",
    "Noun",
    "Particle",
    "Preposition",
    "Pronoun",
    "Pronunciation",
    "Proper noun",
    "Verb",
];

pub const HEADING_BLACKLIST: [&str; 85] = [
    // "Abbreviations", // keep for now
    "Additional notes",
    "Alternative pronunciation", "Alternative Pronunciation",
    "Alternative spellings",
    "Anagrams",
    "Antonyms",
    "Attestations",
    "Circumfix",
    "Collocations",
    "Combining forms", "Combining form",
    "Comeronyms",
    "Common nouns",
    "Composition",
    "Conjugation",
    // "Contraction", // keep for now
    "Coordinate terms",
    "Cuneiform sign",
    "Declension",
    "Derivations",
    "Derivative words",
    "Derived characters", "Derived Characters",
    "Derived forms",
    "Derived glyphs",
    "Derived signs",
    "Derived terms",
    "Derived words",
    "Descendants",
    "Description",
    "Design",
    "Determiner", // keep for now
    "Diacritic",
    "Diacritical mark",
    "Dialects",
    // "Etymology", // keep because there can be multiple
    "Example", "Examples",
    "External links",
    "Formation",
    "Forms",
    "Further reading",
    "Gallery",
    "Glyph origin",
    "Han character",
    "Historical notes",
    "Holonyms",
    "Hypernyms",
    "Hyponyms",
    "Idiom",
    "Interfix",
    "Infix",
    "Letter",
    "Ligature",
    "Links",
    "Meronyms",
    "Multiple parts of speech",
    "Note", "Notes",
    "Number",
    "Numeral",
    "Origin",
    "Other names",
    "Parasynonyms",
    "Paronyms",
    // "Particle", // keep for now
    "Phrase",
    // "Prefix", // keep for now
    // "Prepositional phrase", // keep for now
    "Production",
    "Pron",
    // "Pronunciation", // keep because homophones are in here
    "Pronunciation notes",
    // "Proper nouns", // not sure about this one
    // "Proverb", // not sure about this one
    "Punctuation mark",
    "Quotations",
    "References",
    "Related characters",
    "Related forms",
    "Related symbols",
    "Related terms",
    "See also",
    "Statistics",
    // "Suffix", // keep for now
    "Symbol",
    "Symbol origin",
    "Symbols",
    "Synonyms",
    "Translations",
    "Trivia",
    "Troponyms",
    "Unrelated terms",
    "Usage notes",
];
